apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipe-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AkhilBhavsar/recipe-infra-ca2
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: recipe-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
