apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-backend-blue
  namespace: recipe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-backend
      version: blue
  template:
    metadata:
      labels:
        app: recipe-backend
        version: blue
    spec:
      containers:
      - name: backend
        image: recipeacr9c4b0f.azurecr.io/recipe-backend:fdbbeaa48a756311d55671b6f9a44216a99d4454
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
        - name: MONGO_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_DB_NAME
        - name: MONGO_COLLECTION
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_COLLECTION
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"