apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-frontend-blue
  namespace: recipe-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-frontend
      version: blue
  template:
    metadata:
      labels:
        app: recipe-frontend
        version: blue
    spec:
      containers:
      - name: frontend
        image: recipeacr9c4b0f.azurecr.io/recipe-frontend:f6bfff9a82f13edc7742ac2ecb26b18f2566ed61
        ports:
        - containerPort: 22137
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"