apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: recipe-app
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo:27017"
  MONGO_DB_NAME: "recipes"
  MONGO_COLLECTION: "recipe"